export const GET_ALL_URLS = 'GET_ALL_URLS';
export const GET_ALL_URLS_SUCCESS = 'GET_ALL_URLS_SUCCESS';
export const GET_ALL_URLS_ERROR = 'GET_ALL_URLS_ERROR';

export const CHANGE_URL_FORM = 'CHANGE_URL';

export const CREATE_URL = 'CREATE_URL';
export const CREATE_URL_SUCCESS = 'CREATE_URL_SUCCESS';
export const CREATE_URL_ERROR = 'CREATE_URL_ERROR';

export const DELETE_URLS = 'DELETE_URLS';
export const DELETE_URLS_SUCCESS = 'DELETE_URLS_SUCCESS';
export const DELETE_URLS_ERROR = 'DELETE_URLS_ERROR';

export const DELETE_ERROR = 'DELETE_ERROR';